### ISSUE TITLE
Logguer les connexions

### ISSUE THREAD

**Issue by NTag** [Nadrieril/bars-django#3]
Enregistrer l'historique des connexions : ip, date, user concerné, login envoyé, réussite ou échec.

**Comment by Nadrieril** [comment]
On a déjà la date du dernier login, tu as besoin d'autant ?

**Comment by NTag** [comment]
C’est pour suivre s’il y a eu des abus ou des usurpations. On aura les logs django bruts sinon mais c’est plus pratique d’avoir cet historique isolé. Ça doit pas couter grand chose ?
