### ISSUE TITLE
Ajouter un objet Bug

### ISSUE THREAD

**Issue by NTag** [Nadrieril/bars-django#4]
Camille a ajouté un formulaire pour indiquer un bug. Il faudrait pouvoir les enregistrer :) .

Je propose : {account, date, message, page} (page je sais pas trop encore)

**Comment by tizot** [comment]
On peut enregistrer le state courant en tout cas...
Le ven. 27 févr. 2015 à 13:54, Basile Bruneau <notifications@github.com> a
écrit :

**Comment by Nadrieril** [comment]
Il faudrait aussi indiquer joliment quand il y a une erreur avec le serveur
et proposer d'enregistrer le détail de l'erreur

**Comment by Nadrieril** [comment]
https://github.com/Nadrieril/bars-django/commit/4936a2fe5e9addea3749289d1ca9ede2fec32aab

**Comment by tizot** [comment]
Excellent ! 
Par contre, il reste un problème de permission : on n'a pas le droit de POSTer de BugReport...

**Comment by Nadrieril** [comment]
Pour moi tu peux des que tu es customer. Faudra que je checke
