### ISSUE TITLE
fuzzy_price ne semble pas tenir compte de tax

### ISSUE THREAD

**Issue by NTag** [Nadrieril/bars-django#7]
Je crée un SellItem avec une tax=0.2, puis un StockItem associé avec price=2 et ensuite le fuzzy_price du SellItem est 2.00€ (au lieu de 2.40€).

De plus lorsque je change la taxe du SellItem j'ai l'impression que le fuzzy_price varie très bizarrement.

**Comment by Nadrieril** [comment]
https://github.com/Nadrieril/bars-django/commit/40f7829b8ee61963e77ccfe638c1c200bd8f92ce
